### ISSUE TITLE
Note placement breaks when scrolling/zooming

### ISSUE THREAD

**Issue by DerpyChap** [towai/TromboneCharter#15]
On the current `master` branch, starting up Charter and then attempting to scroll or zoom breaks note placement. If you load an existing chart then this problem doesn't seem to occur (not even when selecting New Chart after).

https://github.com/towai/TromboneCharter/assets/15108194/b3f3830f-3874-487b-aecd-49848da8c943

When this happens the error log is spammed with the following errors:

```gdscript
E 0:00:05:0907   note.gd:225 @ _update(): Condition "!isfinite(p_size.x) || !isfinite(p_size.y)" is true.
  <C++ Source>   scene/gui/control.cpp:1448 @ set_size()
  <Stack Trace>  note.gd:225 @ _update()
                 note.gd:157 @ _process_drag()
                 note.gd:98 @ _process()


E 0:00:05:0915   note.gd:208 @ update_handle_visibility(): Condition "!isfinite(p_size.x) || !isfinite(p_size.y)" is true.
  <C++ Source>   scene/gui/control.cpp:1448 @ set_size()
  <Stack Trace>  note.gd:208 @ update_handle_visibility()
                 note.gd:186 @ update_touching_notes()
                 note.gd:167 @ _end_drag()
                 note.gd:126 @ _process_drag()
                 note.gd:98 @ _process()
```

From a quick check this regression seems to have been added between https://github.com/towai/TromboneCharter/commit/ecd94dc8a2768a2c9f3d81f0b8b54f059a5477e1 and https://github.com/towai/TromboneCharter/commit/aea560cddec08aecde43bc3943fd3a1789584349 (wasn't able to check further).

**Comment by towai** [comment]
Interesting. Based purely on the errors the editor was throwing me I really figured it was due to the changes I made to improve preview performance (namely changing the Chart's bar_spacing to be maintained by itself, rather than accessed via a getter), so I was looking into those. I'll try to bifurcate further.

**Comment by towai** [comment]
Bisect yields that the first bad commit is 5d8a1ce, but there weren't any changes that immediately looked suspicious. It looks like new_note_pos is getting set to a pair of NaNs in _gui_input() when adding a note, because somehow event.position is a pair of NaNs.
the kicker: all this actually works fine when there's a waveform preview and, sure enough, commenting out chart.gd:62 :
https://github.com/towai/TromboneCharter/blob/8b074e7cf060d5ad125c98ed144e1e81cdefb7db/pianoroll/chart.gd#L62
fixes the issue.

Ultimately this was caused by a pretty boneheaded divide by zero case in that function which set WavePreview's horizontal scale to NaN; not totally sure how that should cascade to fucking up the event position for the Chart (even when the WavePreview's mouse filter is set to either "pass" OR "ignore") but it really should've been fixed anyway (or caught when I authored the method in the first place). There may be a better way to check for / have the wave preview maintain knowledge of whether a preview actually exists or not, but at least for now, 9b9d1e8 fixes this.
