### ISSUE TITLE
Latest master branch exports broken charts

### ISSUE THREAD

**Issue by hedgehog1029** [towai/TromboneCharter#17]
In fadd5d097a2453b3efdc08eff5bc8c4d65eec837 the tmb exporter was changed to add the `improv_zones` field. However it appears to have been implemented incorrectly, as it exports JSON files with `"improv_zones": {}`. This is now broken under TrombLoader 2.2.0 as it expects `improv_zones` to be an array.

The offending line is this:

https://github.com/towai/TromboneCharter/blob/c26999626a64d901f2130a74116f678f1af17d3e/tmb_info.gd#L161

Presumably this was meant to reference the `improv_zones` variable instead of being an empty object.

**Comment by towai** [comment]
Known issue; fixes were applied in `toottally` branch though maybe should've been applied to master and then ported over--i've cherrypicked them now (3c79cc2), thanks for pointing it out. i really need to get around to finalizing the changes to that feature (because that wasn't the only other thing that's on that branch!) and merging it anyway.
