### ISSUE TITLE
Can't open due to graphic cards issue.

### ISSUE THREAD

**Issue by mechPenSketch** [towai/TromboneCharter#8]
When I tried to open this software, I got this error message instead:
![trombone](https://user-images.githubusercontent.com/15977859/211303503-59c25107-a771-4009-b88e-2ed61cf4e650.png)
I used trombonecharter_win64.exe 0.9.5 on Windows 10 (base operation x64). For graphics, I'm using AMD FirePro W5100 (FireGL V), which is most likely the cause.

**Comment by mechPenSketch** [comment]
Turns out my GPU can't run Vulkan, which is what Godot 4.0 only renders in thus far. However, [compatibility with OpenGL](https://godotengine.org/article/status-of-opengl-renderer) is in progress, I only have to wait until it's fully implemented.

**Comment by towai** [comment]
It looks as if this is still an issue in 4.x, but I think the more preferable option would be to provide a separate OGL build for people who can't run Vulkan and have the build using Forward+ be the main one. When 4.0 was still in beta I tried the compatibility renderer and it made the program straight up unusable, and even though I'm sure all that's been fixed now I don't see the benefit in a complete switch (there'd likely be performance implications, at the very least)

**Comment by towai** [comment]
I didn't know this at the time, maybe I should've looked into it a bit more than I did, but you can load the existing build with `--rendering-driver opengl3` in the terminal and it will use OpenGL as the renderer. I just had to do this testing the Linux build on a laptop and it worked perfectly (though I didn't try loading TTFAF, which is what I've generally used as a stress test. Just didn't bother copying it to that computer tonight). So that's great—no separate build is even needed, and clearly OpenGL in Godot 4 has made massive strides since a year ago. In future builds I'll include a script (.bat/.cmd for windows, .sh for linux, i'll probably ask DerpyChap about Mac) to launch the program using this option.

EDIT: This has been open long enough I had forgotten about the part where it says your graphics card also doesn't support the supported OpenGL versions (read: 3.0). I still have yet to try this with OpenGL 2.0, then, and see how well it works—I'll try to do that tomorrow. Just a bit odd that on the Linux build it told me to try flipping that switch and then on the Windows side it clearly tries checking if OpenGL 3 is supported. Maybe it would've given me a different error message if that laptop didn't support OpenGL 3 either?

**Comment by towai** [comment]
This is resolved as best as possible by #19 adding an action to export a compatibility build that uses OpenGL 3. Godot 4 does not OpenGL 2 whatsoever (and i'm not sure how exactly i got the idea that it did), but anyone who can't use 3.0 can try the utility DerpyChap mentioned in [this comment](https://github.com/towai/TromboneCharter/pull/19#issuecomment-1841152997).
