### ISSUE TITLE
Waveform background

### ISSUE THREAD

**Issue by flumiie** [towai/TromboneCharter#9]
Is it possible to add waveform backing like this? So, with the waveform it's even easier to chart.
![image](https://user-images.githubusercontent.com/8995187/212273185-2187a91b-c2e8-450c-8320-a781afd61333.png)

**Comment by towai** [comment]
you know, when I saw this I didn't think it was possible within reason, but as it turns out, ffmpeg _does_ have an option to render out a waveform to an image 👀

i'll have to mess around with it and see if i can get something that functions well, but since it does require ffmpeg it's still gonna be an optional/advanced user feature

**Comment by towai** [comment]
if you can download the godot editor, you can try cloning the latest commit and seeing how you like the implementation! (and maybe even build to see if it works in release mode -- i haven't tried this yet myself.) either way, here's a still just to demonstrate what it looks like as of now:

![image](https://github.com/towai/TromboneCharter/assets/12366892/81febbd1-a219-4ba8-a815-0f447fbb8ef6)

long maps can take a while to build the preview in hi-res mode, but afraid not too much can be done about that. if there's nothing else to be improved upon then i'll close this with the next release.

**Comment by flumiie** [comment]
Sure do (sorry for the late response here)

**Comment by towai** [comment]
This feature has been present for a while now; i know i said i'd wait for release, but since thanks to the build action added in 44fdf0c you can try it without even having to wait for a proper release → https://github.com/towai/TromboneCharter/actions/runs/7073708722 i think it's safe to go ahead and close this now
